jobs:
  build:
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        cache: gradle
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
      with:
        node-version: 16
    - continue-on-error: true
      name: Congfigure vega-cli
      run: npm i -g vega-cli --unsafe
    - continue-on-error: true
      name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@b231772637bb498f11fdbc86052b6e8a8dc9fc92
    - continue-on-error: true
      name: Install additional software
      run: 'sudo apt-get update

        sudo apt-get install ghostscript graphviz -y

        '
    - continue-on-error: true
      name: Documentation build
      run: ./gradlew --no-daemon --console=plain doc
name: Fineract Documentation build
on:
  repository_dispatch:
    types: trigger-ga___build-documentation.yml
permissions:
  contents: read
